---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-v1
  target:
    name: atuin-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        ATUIN_DB_URI: |-
          postgres://{{ .ATUIN_DB_USER }}:{{ .ATUIN_DB_PASS }}@{{ .POSTGRES_FULL_HOST }}/{{ .ATUIN_DB_NAME }}

        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .ATUIN_DB_NAME }}"
        INIT_POSTGRES_HOST: "{{ .POSTGRES_FULL_HOST }}"
        INIT_POSTGRES_USER: "{{ .ATUIN_DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .ATUIN_DB_PASS }}"

        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"

  dataFrom:
    - find:
        name:
          regexp: ^POSTGRES_.*
    - find:
        name:
          regexp: ^ATUIN_.*

