---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atuin
spec:
  chartRef:
    kind: OCIRepository
    name: atuin
  interval: 30m
  maxHistory: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      atuin:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: &secret atuin-secret
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.6
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: *secret
        containers:
          app:
            image:
              repository: ghcr.io/atuinsh/atuin
              tag: v18.8.0
            env:
              TZ: ${TZ}
              ATUIN_HOST: 0.0.0.0
              ATUIN_PORT: &port 8080
              ATUIN_OPEN_REGISTRATION: true
            envFrom: *envFrom
            args:
              - server
              - start
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 250Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
    service:
      app:
        controller: atuin
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: atuin
          gethomepage.dev/name: Atuin
          gethomepage.dev/group: Development
          gethomepage.dev/description: Shell history sync and search
        hostnames: ["atuin.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    persistence:
      config:
        type: emptyDir
