---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres16
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.8
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: ceph-block
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-secret
  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      cpu: 500m
    limits:
      memory: 4Gi

  postgresql:
    shared_preload_libraries:
      - "vectors.so"
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
