---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rook-ceph-cluster
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: rook-ceph-cluster
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
    - name: snapshot-controller
      namespace: system
  values:
    toolbox:
      enabled: true

    monitoring:
      enabled: true
      createPrometheusRules: true

    route:
      dashboard:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Ceph"
          gethomepage.dev/group: "System"
          gethomepage.dev/icon: "ceph"
          gethomepage.dev/description: "Rook-Ceph Dashboard."
          gethomepage.dev/pod-selector: >-
              app.kubernetes.io/name in (ceph-mgr)
        host:
          name: "rook.${SECRET_DOMAIN}"
          path: /
          pathType: PathPrefix
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    cephClusterSpec:
      cephConfig:
        global:
          bdev_enable_discard: "true" # quote
          bdev_async_discard_threads: "1" # quote
          osd_class_update_on_start: "false" # quote
          device_failure_prediction_mode: local # requires mgr module
        mgr:
          mgr/crash/warn_recent_interval: "7200" # 2h

      crashCollector:
        disable: false

      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false

      mgr:
        modules:
          - name: diskprediction_local
            enabled: true
          - name: insights
            enabled: true
          - name: pg_autoscaler
            enabled: true
          - name: rook
            enabled: true

      resources:
        mgr:
          limits:
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 500Mi
        mon:
          limits:
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 500Mi
        osd:
          limits:
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 1500Mi
        mgr-sidecar:
          limits:
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 40Mi
        crashcollector:
          limits:
            memory: 60Mi
          requests:
            cpu: 100m
            memory: 10Mi
        logcollector:
          limits:
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 100Mi
        cleanup:
          limits:
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 100Mi

      storage:
        useAllNodes: true
        useAllDevices: false
        deviceFilter: sda
        config:
          osdsPerDevice: "1"

    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
          mountOptions:
            - discard
          parameters:
            imageFormat: "2"
            # TODO: enable these features on next rebuild
            #imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/fstype: ext4

    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-blockpool
      isDefault: false
      deletionPolicy: Delete
    cephFileSystems: []
    cephObjectStores: []
