---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app freshrss
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      freshrss:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          hostUsers: false
        containers:
          app:
            image:
              repository: freshrss/freshrss
              tag: 1.26.3-alpine
            env:
              CRON_MIN: "*"
              DOMAIN: "{{ .Release.Name }}.internal.${SECRET_DOMAIN}"
              LISTEN: &port 8080
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          freshrss:
            app:
              - path: /var/www/FreshRSS/data
                subPath: data
                readOnly: false
              - path: /var/www/FreshRSS/extensions
                subPath: extensions
                readOnly: false
    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: freshrss
          gethomepage.dev/name: Freshrss
          gethomepage.dev/group: Self-Hosted
          gethomepage.dev/description: RSS feed
        hosts:
          - host: &host "{{ .Release.Name }}.internal.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
