---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-v1
  target:
    name: crowdsec-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        http.yaml: |
          type: http
          name: http_default

          log_level: info

          #-------------------------
          # plugin-specific options

          format: |
            {{ range . -}}
            {{ $alert := . -}}
            {
              "extras": {
                "client::display": {
                "contentType": "text/markdown"
              }
            },
            "priority": 3,
            {{range .Decisions -}}
            "title": "{{.Type }} {{ .Value }} for {{.Duration}}",
            "message": "{{.Scenario}}  \n\n[crowdsec cti](https://app.crowdsec.net/cti/{{.Value -}})  \n\n[shodan](https://shodan.io/host/{{.Value -}})"
            {{end -}}
            }
            {{ end -}}

          url: https://gotify.internal.{{ .SECRET_DOMAIN }}/message

          method: POST

          headers:
            X-Gotify-Key: {{ .GOTIFY_CROWDSEC_API_KEY }}
            Content-Type: application/json

  dataFrom:
    - find:
        name:
          regexp: ^GOTIFY_CROWDSEC.*
