---
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file: bootstrap/**/*
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
area/github:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: kubernetes/**/*
area/renovate:
  - changed-files:
      - any-glob-to-any-file:
          - ".renovate/**/*"
          - ".renovaterc.json5"
area/scripts:
  - changed-files:
      - any-glob-to-any-file:
          - scripts/**/*
          - scripts/*.sh
area/talos:
  - changed-files:
      - any-glob-to-any-file: talos/**/*
      - any-glob-to-any-file: talos/*.yaml
area/taskfile:
  - changed-files:
      - any-glob-to-any-file:
          - ".taskfiles/**/*"
          - "Taskfile.yaml"
area/templates:
  - changed-files:
      - any-glob-to-any-file: templates/**/*
