---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crowdsec
  namespace: security
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/apps/security/crowdsec/app"
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
