---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-relay
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-v1
  target:
    name: smtp-relay-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        SMTP_RELAY_SERVER: "{{ .SMTP_RELAY_SERVER }}"
        SMTP_RELAY_USERNAME: "{{ .SMTP_RELAY_USERNAME }}"
        SMTP_RELAY_PASSWORD: "{{ .SMTP_RELAY_PASSWORD }}"
  dataFrom:
    - find:
        name:
          regexp: ^SMTP_RELAY.*
