---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-v1
  target:
    name: gotify-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:

        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .GOTIFY_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: "{{ .GOTIFY_POSTGRES_DB_HOST }}.database.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .GOTIFY_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .GOTIFY_POSTGRES_PASSWORD }}"

        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        # App
        GOTIFY_DEFAULTUSER_NAME: "{{ .GOTIFY_DEFAULTUSER_NAME }}"
        GOTIFY_DEFAULTUSER_PASS: "{{ .GOTIFY_DEFAULTUSER_PASS }}"

        # Database
        GOTIFY_DATABASE_CONNECTION: |-
          host='{{ .GOTIFY_POSTGRES_DB_HOST }}.database.svc.cluster.local' port='5432' user='{{ .GOTIFY_POSTGRES_USER }}' dbname='{{ .GOTIFY_POSTGRES_DB }}' password='{{ .GOTIFY_POSTGRES_PASSWORD }}'



  dataFrom:
    - find:
        name:
          regexp: ^POSTGRES.*
    - find:
        name:
          regexp: ^GOTIFY.*
