apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify
  namespace: monitoring
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
