# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZcZKIo3s21GmgekRIK7LIirtqIiXVvyUER7VFyP/Y5tE2DGnCQ8UPg==,iv:c0L1/QMiyhwDqNyM39NFIyICZYMVjZlRugzK43Gt6t8=,tag:oVSEXjkavnPKV5vTyVBY9A==,type:str]
sops:
  age:
    - recipient: age1ay2q0nmvmn00eefg57j85zz8a5eyuecuzcmkfzqtrvmpjc47cpmq25yn0q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2K1JndjQ5SU5CbWZKRjVy
        R3p2OGpyQlJWbTlsOHBOcFh4Z09HVHVEM0JVCjBOdU9MUjA3SHQzTC8zV1gzd3pz
        K2ZQRkNnTGRPZUxFeC95bzZibGZXM1EKLS0tIEZIblVoRldLWVhnY0hhZWZPMXFs
        UVVnRGt1SDZpUFI5UEhHR1JITTdNVDQKQzYWdgh9VrfF0PHDqye9/P8Sq0J7IqJL
        xiFYJyitjgf3PKJZdkWiBRfaTENzz2oUDpUHkgjkHl4kJYrDziKwag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-13T19:24:48Z"
  mac: ENC[AES256_GCM,data:taAyFdklG/zqpHR3q0b7MYk+mswevU/txqfVNO0pvE5inIs0vctazE9auOOppVJuNq74+Rm8RKNgZsvlyBbpVcWQN8B9hh2i7OXHr2Ws8XQxeBxIYwFMjiEcumelK67hau+/0nhME9CN5n8ZQ22QUzasIk75k0PifrO7cSX1m+Q=,iv:BsG5qffWQZnt8buJJv5eGS8Q4ikwTWx8c28t6+x1sSw=,tag:i/ccYO5b8WGkh85G5KqTMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
