# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:uSHRsAnNtm9eK3WftU5Z1XnuLxZk7v9WSGp0e4QT+4w=,iv:n3Lp8MIEhNmCcw9ax++/GyUtP2fk5CUyIJNaScf15i4=,tag:qVRlcNHqM8sjoHBRgQipqg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ay2q0nmvmn00eefg57j85zz8a5eyuecuzcmkfzqtrvmpjc47cpmq25yn0q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrLzNRTC9YQWVwRkh0T3l4
        ck9YZy9KTnY3TkZFQVpJUld4WDlmc3JBVDJjCmh0OEZnQ3BVZWRMdDF3NEtTYXRn
        YUE1WnNUZGZFQ1lnSUpuaEJpM01JSGcKLS0tIEhDOHdySU5ETFlQeFV2MlY1bzYy
        WmJ4K2UweHZmRnovMFFxRWJSdFVrYkEKg9XL/l8VEs0hnCvYKMKkYP05EDfUyoNW
        3hppL9WejSttDu0m+ZQXhhUMs/u3erIjyiIHewj2+4u7GhxpXncY2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-21T17:51:06Z"
  mac: ENC[AES256_GCM,data:E/wrTG5p7mKTWwk6I9t3zu7koh/C38r1MfBhXkBl4P3LKCuBwHWRO5VPLPq3FB/lqaMlldXCetTxEBHMeXPvP6JW2AqevN9wzvO23WWPMUrrMm7ojYGIV6dEIHABWEpclhESdyw0P5AQasdnV4oSSk4GeAh6dDNvXJNMdGW644k=,iv:TA3ZGnpgo8LDSGOIFVdmTP6N2HgdGTkQUOsAbpGU840=,tag:ZN3w2avt8LVYOkgkp2THTA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
