apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget
  namespace: finance
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
