---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: *name
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        AUTHENTIK_POSTGRESQL__HOST: &dbhost "{{ .POSTGRES_SUPER_HOST_RW }}.database.svc.cluster.local"
        AUTHENTIK_POSTGRESQL__NAME: &dbname "authentik"
        AUTHENTIK_POSTGRESQL__USER: &dbuser "{{ .POSTGRES_USER  }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbpass "{{ .POSTGRES_PASSWORD  }}"

        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .AUTHENTIK_BOOTSTRAP_EMAIL }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .AUTHENTIK_BOOTSTRAP_PASSWORD }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .AUTHENTIK_BOOTSTRAP_TOKEN }}"
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"

        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass

        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - find:
        path: POSTGRES_USER
    - find:
        path: POSTGRES_PASSWORD
    - find:
        path: AUTHENTIK_BOOTSTRAP_EMAIL
    - find:
        path: AUTHENTIK_BOOTSTRAP_PASSWORD
    - find:
        path: AUTHENTIK_BOOTSTRAP_TOKEN
    - find:
        path: AUTHENTIK_SECRET_KEY
    - find:
        path: POSTGRES_SUPER_PASS
    - find:
        path: POSTGRES_SUPER_HOST_RW
