---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: 2025.8.3
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: *secret
        - secretRef:
            name: &secret-postgres authentik-postgres-secret
    redis:
      enabled: true
    server:
      replicas: 1
      initContainers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:17.6
          envFrom:
            - secretRef:
                name: *secret-postgres
      autoscaling:
        enabled: true
        minReplicas: 1
      resources:
        requests:
          cpu: 200m
        limits:
          memory: 1Gi
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
    worker:
      autoscaling:
        enabled: true
        minReplicas: 1
      resources:
        requests:
          cpu: 200m
        limits:
          memory: 1Gi
    prometheus:
      rules:
        enabled: false
