---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gitea
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      gitea:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: gitea-secret
        containers:
          app:
            image:
              repository: ghcr.io/go-gitea/gitea
              tag: 1.24.6-rootless
            env:
              GITEA__SERVER__DOMAIN: "gitea.${SECRET_DOMAIN}"
              GITEA__SERVER__ROOT_URL: "https://gitea.${SECRET_DOMAIN}"
              GITEA__SERVER__SSH_DOMAIN: "ssh.${SECRET_DOMAIN}"
              GITEA__SERVER__SSH_PORT: 22
              GITEA__SERVER__HTTP_PORT: &port 3000

              # Change next 2 lines if want a new user
              GITEA__SERVICE__DISABLE_REGISTRATION: "true"
              # GITEA__SERVICE__ENABLE_AUTO_REGISTRATION: "true"
              GITEA__MIGRATIONS__ALLOW_LOCALNETWORKS: "true"
              ENABLE_PASSWORD_SIGNIN_FORM: "false"
              ENABLE_BASIC_AUTHENTICATION: "false"

              TZ: ${TZ}

              GITEA__MAILER__PROTOCOL: "SMTP"
              GITEA__MAILER__SMTP_ADDR: "smtp-relay.network.svc.cluster.local"
              GITEA__MAILER__SMTP_PORT: "8080"
              GITEA__MAILER__FROM: "gitea@${SECRET_DOMAIN}"
            envFrom: *envFrom
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65536
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: gitea
          gethomepage.dev/name: Gitea
          gethomepage.dev/group: Development
          gethomepage.dev/description: Self-hosted code storage service
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          gitea:
            app:
              - path: /var/lib/gitea
                subPath: data
              - path: /etc/gitea
                subPath: config
      tmp:
        type: emptyDir
    service:
      app:
        # TODO: Walkaround for SSH access.
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.31.112
        controller: *app
        ports:
          http:
            port: *port
          ssh:
            port: 22
            protocol: TCP
            targetPort: 2222
