---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-vikunja
  target:
    name: vikunja-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        VIKUNJA_SERVICE_JWTSECRET: "{{ .VIKUNJA_SERVICE_JWTSECRET }}"
        VIKUNJA_DATABASE_TYPE: postgres
        VIKUNJA_DATABASE_SSLMODE: require
        VIKUNJA_DATABASE_HOST: &dbHost "{{ .VIKUNJA_DATABASE_HOST }}.database.svc.cluster.local"
        VIKUNJA_DATABASE_DATABASE: &dbName "{{ .VIKUNJA_DATABASE_DATABASE }}"
        VIKUNJA_DATABASE_USER: &dbUser "{{ .VIKUNJA_DATABASE_USER }}"
        VIKUNJA_DATABASE_PASSWORD: &dbPass "{{ .VIKUNJA_DATABASE_PASSWORD }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass

  dataFrom:
    - find:
        name:
          regexp: ^VIKUNJA.*

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-postgres
  target:
    name: vikunja-db-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        # Postgres Init
        INIT_POSTGRES_HOST: "{{ .VIKUNJA_DATABASE_HOST }}.database.svc.cluster.local"
        INIT_POSTGRES_DBNAME: "{{ .VIKUNJA_DATABASE_DATABASE }}"
        INIT_POSTGRES_USER: "{{ .VIKUNJA_DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .VIKUNJA_DATABASE_PASSWORD }}"

        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"

  dataFrom:
    - find:
        name:
          regexp: ^POSTGRES.*
    - extract:
        key: vikunja-secret
