---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vikunja
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      vikunja:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: &secret vikunja-secret
        containers:
          app:
            image:
              repository: vikunja/vikunja
              tag: 0.24.6@sha256:ed1f3ed467fecec0b57e9de7bc6607f8bbcbb23ffced6a81f5dfefc794cdbe3b
            envFrom:
              - secretRef:
                  name: vikunja-secret
            env:
              VIKUNJA_SERVICE_PUBLICURL: &host "todo.${SECRET_DOMAIN}"

              # SMTP
              VIKUNJA_MAILER_HOST: smtp-relay.network.svc.cluster.local
              VIKUNJA_MAILER_PORT: 25
              VIKUNJA_MAILER_FROMEMAIL: alerts@${SECRET_DOMAIN}
            resources:
              requests:
                cpu: 5m
                memory: 10Mi
              limits:
                memory: 100Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 3456
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Vikunja
          gethomepage.dev/description: Tasks and project management platform.
          gethomepage.dev/group: Productivity
          gethomepage.dev/icon: vikunja.png
        hostnames: ["todo.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /app/vikunja/files

      vikunja-config:
        type: secret
        name: *secret
        globalMounts:
          - path: /app/vikunja/config.yaml
            subPath: config.yaml
            readOnly: true
