apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja
  namespace: default
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
