# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:qkFgARdjI7UgKWHGe78ksyX2vraW1S7zi2s4Wxx4dcYqeRwJvrF8YJaEyFQa+QFAF9/wGcMYkIJNJDgXk37i2D8oUWygMV6X6YHQkbaKhLLpl/LDFfI/t5WIWe6UeVjY4H+vZjxlBqipQBdXjRV9fnSNwBOxfvL6xKSb7eMybJ7IP/LXlKeZMh1k82GSxE7P+qZKLjQ/k2dl8w7l0U2SxIC7eN9tFh1R/xaufc7Q/YkPh2Mf,iv:T2U0+AEWXuVAWpj0pZOMjdGpJfpciNNQnElb+ROMbcc=,tag:0iDIKvZnVsLqIyAJYQXw3w==,type:str]
sops:
  age:
    - recipient: age1ay2q0nmvmn00eefg57j85zz8a5eyuecuzcmkfzqtrvmpjc47cpmq25yn0q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZGdYdUd0MnRHSjRtUllN
        MHB2NTdmUmpRdEFZREZxNjNjaTFwbXpSaFNFCkNObmR3MDlPaHNZM0NQQ1NNWThv
        aVNqR2QvbzRkaGFVcVRXSEhuTUNocjQKLS0tIEExanZqWVp0QjczL1NCTlduQjJo
        OWIrVjFVdnNtSUhRSkhTazFsR3NxOU0Ko2dqppWkuC6zXzSyFOqwyKjUPwupBDca
        4Xpy3MuPOPjLdMNyuHHpSt0nuCQyIMtWffaRa9hHANcFpcNSZSsUYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-13T19:40:59Z"
  mac: ENC[AES256_GCM,data:zA25COfZW7zNtm4cx6nx+W5MybwLe6he9sCQuMbpMNAgKxK0XVeE1nFJquKVm6zS7desEY4pudqfvflyAizLDCkwuk4ieVE9KYazGDZqFb3MBSCePOzgzDrZe9UyRFmKbAx/8ZE08aO17ks/bxHLi/djBdRk1ecZd7btpCExJd0=,iv:O+YabshPfMB40GpDb6LhyT0EwgfCEQfYnH1QC/brGDM=,tag:edWoTAIFNNN7Y9XoDvVPRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
