---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
components:
  - ../../components/common
resources:
#  - ./crowdsec/ks.yaml
  - ./infisical-secrets/ks.yaml
  - ./external-secrets/ks.yaml
  - ./authentik/ks.yaml
  - ./tailscale-operator/ks.yaml
