---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxies
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-v1
  target:
    name: proxies-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PROXY_IMMICH_IP:  "{{ .PROXY_IMMICH_IP }}"
        PROXY_IMMICH_PORT:  "{{ .PROXY_IMMICH_PORT }}"

  dataFrom:
    - find:
        name:
          regexp: ^PROXY.*
