---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/master/service.json
apiVersion: v1
kind: Service
metadata:
  name: &name nas
  labels:
    app: *name
spec:
  ports:
    - name: http
      port: 80
      targetPort: ${PROXY_NAS_PORT}
      protocol: TCP
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/master/endpoints.json
apiVersion: v1
kind: Endpoints
metadata:
  name: nas
subsets:
  - addresses:
      - ip: ${PROXY_NAS_IP}
    ports:
      - port: ${PROXY_NAS_PORT}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &name nas
spec:
  hostnames:
    - nas.${SECRET_DOMAIN}
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: *name
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /

