---
apiVersion: v1
kind: Service
metadata:
  name: &name immich
  labels:
    app: *name
spec:
  ports:
    - name: http
      port: 80
      targetPort: ${PROXY_IMMICH_PORT}
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: immich
subsets:
  - addresses:
      - ip: ${PROXY_IMMICH_IP}
    ports:
      - port: ${PROXY_IMMICH_PORT}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &name immich
spec:
  hostnames:
    - photos.${SECRET_DOMAIN}
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: *name
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
