---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lubelog
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-v1
  target:
    name: lubelog-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        # Init DB
        INIT_POSTGRES_DBNAME: "{{ .LUBELOG_DB_NAME }}"
        INIT_POSTGRES_HOST: "{{ .POSTGRES_FULL_HOST }}"
        INIT_POSTGRES_USER: "{{ .LUBELOG_DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .LUBELOG_DB_PASS }}"
        POSTGRES_CONNECTION: 'Host={{ index . "POSTGRES_FULL_HOST" }}:5432;Username={{ .LUBELOG_DB_USER }};Password={{ .LUBELOG_DB_PASS }};Database={{ .LUBELOG_DB_NAME }}'

        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"

  dataFrom:
    - find:
        name:
          regexp: ^POSTGRES_.*
    - find:
        name:
          regexp: ^LUBELOG_.*
