---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lubelog
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      lubelog:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.6@sha256:86a1992d46273c58fd4ad95b626081dfaabfe16bd56944675169e406d1a660dd
            envFrom: &envFrom
              - secretRef:
                  name: lubelog-secret
        containers:
          app:
            image:
              repository: ghcr.io/hargata/lubelogger
              tag: v1.5.1
            env:
              TZ: ${TZ}
              # SMTP Settings
              MailConfig__EmailServer: "smtp-relay.services.cluster.local"
              MailConfig__EmailFrom: "alerts@${SECRET_DOMAIN}"
              MailConfig__Port: "25"
              MailConfig__Username: "Lubelog"
            envFrom: *envFrom
            resources:
              requests:
                cpu: 15m
                memory: 80M
              limits:
                memory: 256M
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8080
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Self-Hosted
          gethomepage.dev/name: lubelog
          gethomepage.dev/icon: https://demo.lubelogger.com/defaults/lubelogger_icon_72.png
          gethomepage.dev/description: Car Service Tracking

        hostnames: ["lubelog.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      app:
        existingClaim: *app
        globalMounts:
          - path: /App/config
            subPath: config
          - path: /App/data
            subPath: data
          - path: /App/wwwroot/translations
            subPath: translations
          - path: /App/wwwroot/documents
            subPath: documents
          - path: /App/wwwroot/images
            subPath: images
          - path: /App/log
            subPath: log
          - path: /root/.aspnet/DataProtection-Keys
            subPath: keys
      tmp:
        type: emptyDir
        globalMounts:
          - path: /App/wwwroot/temp
            readOnly: true
