apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:KQNu5YCVuA==,iv:+WPs9IuDTOzORzEEv6Tk1C48tnEXPTOWTYAPkNkkE6I=,tag:hfkN6hb6pzh3PZtkOd0v1g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ay2q0nmvmn00eefg57j85zz8a5eyuecuzcmkfzqtrvmpjc47cpmq25yn0q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbWZ6K05HK2VBbmZMNUZo
        bzVNN05yOVQwMkNyZS9pNWdFSmY2OWNRL3hrCmdZc3ByME1hVWIzWU94VXZXN0Nr
        QWQxek8ycmRmVlArVkJPSE0vN0t1Z1UKLS0tIFdJWVdLMEpUSVIveWdjWHoxTU14
        OGdYYjFUY3dqZFdZZHQxTzRUM2cva0EKFE/PRFFc35ZWio6Z32auIFvVs2WYr4CU
        sLDwPFsRSGp4hDulUTW+HCNPkUv8bUlMOQ7UtTkFUztWJnfJzW8L5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-21T17:51:06Z"
  mac: ENC[AES256_GCM,data:nz/XVgshKeVQBMI9kx/CWMwjYni46MhjUTVIpprmEUdQejEW+fhZIdnE3tFAYOcAhwBV3qcJCj2jUDGbe5QTpP7c+dvOmGAvVqUP/xb8cE6fqcuIIuckCixzqy1Bor8QiD9buOAzusfGioyNcuzWiWXCE5NPnRmIvg6Bu0/qQ9g=,iv:qNeYvgL53b5rElzC9dJIAiuuofchtPprmB/6OIROV3s=,tag:wAbYYCrUdYMyx7a4QIic4Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
