apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:gyD9GAJE/g==,iv:f9dSr9wvXkyfKFFrR4kDK2C+G7Fd1n1THzFqT4U7OYU=,tag:eu40aP6cBUX+JC4Q9iU3dg==,type:str]
  NFS_IP: ENC[AES256_GCM,data:6dShTFwWfqskTcLnvg==,iv:l17ZAl3RcKApTgMsk91+PldkQI3KvZi0vOO8VsGrHsE=,tag:MhgPeVbvZ+IDYKXgxxOMdQ==,type:str]
sops:
  age:
    - recipient: age1ay2q0nmvmn00eefg57j85zz8a5eyuecuzcmkfzqtrvmpjc47cpmq25yn0q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibFROM2JPQnNxNW9tdTQ3
        Y2wrQVpDYjA0dXUvOE5oSFMydUdDcjBQWUdjCkRjY2VuY2NUL0M5UVhxVHh5RXhu
        engyeUp2bVU4bEVhZ0lHQWVkUnNnejQKLS0tICs1dGZzZm5EblBqNVlwaU9XU1Yx
        MU0zQVd2dzdCNk5ESEV4bXFycUQvNncKwegHb0G08JJKSfTTxJkiyGWWd4g3hIh4
        rxl2MoYr092phRkXi14+gHFh1OTIKKy+Il+EWDAOSjazgWuoE0ddNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-02T19:35:38Z"
  mac: ENC[AES256_GCM,data:1IaBQFJJIVJB6kISTapJUEds1iRB1dN91KbSFcrzwJAm2xHeqQCFmYxp4bMuDa1ZSwWCSG8pq4ZhbzbqggfiWwqAwq54FFq6CLyJdVlDiZYbuLhjXSzRkTJjv9Tcuoc9p+joU25aEnG5PNPzJEj9cVuxI4A6Vpt6+/HQ3e/GIwc=,iv:0Qd3YtcFDxFZxxmAGkROWs3a0ls87O1JNlf9Ct8P8K0=,tag:v/QOLKO5KT1U0cwZDepKig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
