apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:oizU+zAyOg==,iv:j46ZZyO962rqfUiN50Qshb03HVx8dkeVOnNuQobmnaA=,tag:YnTJ4qO31LFRSU/owDLD4Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ay2q0nmvmn00eefg57j85zz8a5eyuecuzcmkfzqtrvmpjc47cpmq25yn0q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQjJPZ2kzTVM5M3lFbGNl
        MVlwVVlrbzhEcTd2YzVvL0V0cndqaWRVY21RCjFBdDBhbG0wV3VQQW1xd05FdHg1
        dkZ5VEVmRHF4UnhvL3hGTUMvV1NqdjQKLS0tIC9vZENoaXpjOGJKU2p3Yms3cEc4
        a2VPcUVjZTE3TnVldWV2K3U5N1djYVkKqaMmAALTkOuP50zkT6VfUcZdowR1GZPy
        dZOQYkf5UxdfguNfw1WW9bKdjJOrea57dm8mrMDTQFgaKlhWh6SVTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-21T18:51:33Z"
  mac: ENC[AES256_GCM,data:d+GWwTOCrWjqKYoDeh3SXQ48pacaf+sCBTbjr+ZNfOWkHBXt8gBdYs7T0fR19ekMsV2r/NQ7LzO+S//vvCmpIf98tJuXJSLxDfMhqfbfRE/iLGeJxcohgv9hM7JCn9FenC5kUCv3Dyt8tFbBLDwt84YD7835dhrS0dqPlFU+FT8=,iv:d1zEJ3D6oAr2O+0shSRhDRONl4eaRdiwR5kCNNEXeVg=,tag:ftKvz+6Yh7l4YaWDaZV6Pg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
