apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:SjIxi5Yat68XAsHFni6xkv15pDRPqdQVo/knq+oVVGtjTycSMeuHVA==,iv:YT/qx+RMLXu2yzgVgf4ptOHdFxPewmCrY+dRmVl0rLI=,tag:n0r9m6r9D0AS9GtiQFl//g==,type:str]
sops:
  age:
    - recipient: age1ay2q0nmvmn00eefg57j85zz8a5eyuecuzcmkfzqtrvmpjc47cpmq25yn0q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUzJrOXFQV0dQUGorcVNh
        MzdObEFCL1k1cWNibllzNXFXYzl3MmZ6dkM0ClgxaG1mdXJUMWpZWU5Cb1NQNWcy
        Qko2cUxMK2hES0xNRld1Z3gvRVByNGMKLS0tIHVJelR4SGNjQThYQVFyT0FNbElN
        WEFxUS9VVUs1WUpOc2daSUdyUkNENVkKjbP/Hcsd6CPWXSUnFf1wTwLNw4RsoTOQ
        bQUyIgPdfb32O3PHchopkmvMxbWql6EvGrMlDZxtkumyvQWKV9a/sQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-22T19:37:21Z"
  mac: ENC[AES256_GCM,data:3Uv/kTYAN9aHYRqFsx6avgJ7W5V/jB7/8cUWravvxCF8nugtkaDrW+7D3HdgigAvGp6AkRFyU+3VqsCTkWVW+4raDNFv/OZvogDr9JZHXFVU37tjXW9XmWPAh7EXg0zcUvdmSjp+/fYpNgW+P/lfg5TrawLcCoX2BSvRIU3OS94=,iv:r2HIep4MNcMNaryKRQgXSG2FghtuYmsZE8l5J8Hf7tw=,tag:iGzJWkU9xsRK/JfZp8qFZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
