# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0yTHm9lSg4CGibD2oa4AprvxJiqaTtAbQg7nxei6dj+qIGNTRY/nQg==,iv:wHBoZLUSpxxZW0aIhf8Mroe6QC7HMwPEh6MRsjNQnHg=,tag:DJRHYbVrZ7EPum+a7XhQQA==,type:str]
sops:
  age:
    - recipient: age1ay2q0nmvmn00eefg57j85zz8a5eyuecuzcmkfzqtrvmpjc47cpmq25yn0q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArd1dKZ2VFVkhoczJHbUNz
        SHJLVVE2T2w5VEdOTVVYQWhvREJxRW9UckI0Cmd3dUJFRUdScm1uKzBsRlE5N1JH
        WkZLaWFiL3QvSjlYd25DQVNVREVPUDQKLS0tIE51RGJQUFhGaTBMTi9wOEJoQWVk
        SWllaEF1QnlUaUxDODJNK0NiNnQ2OGcK+so1AttO4o6cZVErOtRwJJnSySVmXz0Z
        veqsX6XeucSV5boZeJphHhiSbDpqfsQBaYlbgk19RWlWOCoYg1BDJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-13T21:15:23Z"
  mac: ENC[AES256_GCM,data:EGz15mkHWdSiA8aGDZrsdKPNG+DJAd8h/oh4UQE8Ho43JUkzyvOvafTCAlys40F6GTIBtZ/8TZNXNzSMh6wo2wiZDtemUbm1GRcjv25K3tGdd8MCCRsT85x/mMRWQoMdTCcticfAyWgnMdMmU5pQhIfCaO2fNIPICUe7xu96SXY=,iv:C6awNMKda83BVOvEyfg7jXZjjXQT/+98iOBsDUBdt90=,tag:uijJLqToJL3wjI0vveLQzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
