---
- Smart-Home:
    - Home-Assistant:
        # TODO: Migrate to actual address
        href: http://homeassistant.local:8123/
        icon: home-assistant.png
        description: Home Automation Software
        widget:
          type: homeassistant
          url: http://homeassistant.local:8123
          key: {{HOMEPAGE_VAR_HASS_TOKEN}}
    - Frigate:
        href: https://frigate.${SECRET_DOMAIN}
        icon: frigate-light.png
        description: Video Security Software
- Self-Hosted media:
    - TrueNas:
        href: https://nas.${SECRET_DOMAIN}
        icon: truenas.png
        description: NAS Software
    - Jellyfin:
        href: https://jellyfin.${SECRET_DOMAIN}
        icon: jellyfin.png
        description: Home Media Software
    - Immich:
        href: https://photos.${SECRET_DOMAIN}
        icon: immich.png
        description: Self-hosted photos
- System:
    - Mikrotik:
        href: https://router.${SECRET_DOMAIN}
        icon: mikrotik-light.png
        description: Router WEB UI
    - Proxmox:
        href: https://proxmox.${SECRET_DOMAIN}
        icon: proxmox-light.png
        description: VM management
    - Nginx Proxy Manager:
        href: https://nginxpm.${SECRET_DOMAIN}
        icon: nginx-proxy-manager.png
        description: Nginx Proxy Management
    - Cloudflared:
        href: https://dash.cloudflare.com/
        icon: cloudflare-zero-trust.png
        description: Cloudflared Tunnel
        widget:
          type: cloudflared
          accountid: {{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID}}
          tunnelid: {{HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID}}
          key: {{HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN}}
- Extras:
    - Wavelog:
        href: http://wavelog.lan/
        icon: booklogr.png
        description: Ham radio logging software
    - Actual Budget:
        href: https://budget.${SECRET_DOMAIN}
        icon: actual-budget.png
        description: Budgeting tool
