---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: obsidian-couchdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-v1
  target:
    name: obsidian-couchdb-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        COUCHDB_USER: "{{ .OBSIDIAN_COUCHDB_USER }}"
        COUCHDB_PASSWORD: "{{ .OBSIDIAN_COUCHDB_PASSWORD }}"

  dataFrom:
    - find:
        name:
          regexp: ^OBSIDIAN.*
