---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app obsidian-couchdb
  namespace: database
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      obsidian-couchdb:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 150
            fsGroup: 140
            fsGroupChangePolicy: "OnRootMismatch"

        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/busybox
              tag: latest@sha256:ab33eacc8251e3807b85bb6dba570e4698c3998eca6f0fc2ccb60575a563ea74
              pullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
              - "cp /tmp/config/*.ini /opt/couchdb/etc/default.d/; ls -lrt /opt/couchdb/etc/default.d;"

        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/couchdb
              tag: 3.5.0
            envFrom:
              - secretRef:
                  name: obsidian-couchdb-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 200m
                memory: 250M
              limits:
                memory: 500M
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 5984
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: obsidian
          gethomepage.dev/name: Obsidian DB
          gethomepage.dev/group: Database
          gethomepage.dev/description: Local Obsidian Sync Storage
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        enabled: true
        type: configMap
        name: obsidian-couchdb-configmap
        advancedMounts:
          obsidian-couchdb:
            init-config:
              - path: /tmp/config
      data:
        enabled: true
        existingClaim: obsidian-couchdb
        advancedMounts:
          obsidian-couchdb:
            app:
              - path: /opt/couchdb/data
      config-storage:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /opt/couchdb/etc/default.d
