apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-couchdb
  namespace: database
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
