---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bytestash
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-v1
  target:
    name: bytestash-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        JWT_SECRET: "{{ .BYTESTASH_JWT_SECRET }}"

        # Authentik integration
        OIDC_ENABLED: "true"
        OIDC_DISPLAY_NAME: "Authentik"
        OIDC_ISSUER_URL: "https://sso.pouv.uk/application/o/bytestash/"
        OIDC_CLIENT_ID: "{{ .BYTESTASH_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .BYTESTASH_OIDC_CLIENT_SECRET }}"

  dataFrom:
    - find:
        name:
          regexp: ^BYTESTASH_.*

