apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bytestash
  namespace: dev
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
