apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine
  namespace: self-hosted
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
