---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: infisical-charts
spec:
  interval: 2h
  url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
