---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communicate:
        - Discord:
            - icon: discord.png
              href: 'https://discord.com/app'
        - Mail:
            - icon: proton-mail.png
              href: 'https://account.proton.me/mail'
    - Media:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
        - Spotify:
            - icon: spotify.png
              href: 'http://open.spotify.com'
    - Reading:
        - Reddit:
            - icon: reddit.png
              href: 'https://reddit.com'
    - Devops:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: 'https://kubesearch.dev/'
        - home-ops:
            - icon: github.png
              href: 'https://github.com/evjak/home-ops'
        - dashboard-icons:
            - icon: github.png
              href: 'https://github.com/homarr-labs/dashboard-icons/blob/main/ICONS.md'
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Smart-Home:
        - Home-Assistant:
            # TODO: Migrate to actual address
            href: http://homeassistant.local:8123/
            icon: home-assistant.png
            description: Home Automation Software
            widget:
              type: homeassistant
              url: https://homeassistant.local:8123
              key: {{HOMEPAGE_VAR_HASS_TOKEN}}
        - Frigate:
            href: https://frigate.${SECRET_DOMAIN}
            icon: frigate-light.png
            description: Video Security Software
    - Self hosted media:
        - TrueNas:
            href: https://nas.${SECRET_DOMAIN}
            icon: truenas.png
            description: Self-hosted NAS system
        - Jellyfin:
            href: https://jellyfin.${SECRET_DOMAIN}
            icon: jellyfin.png
        - Immich:
            href: https://photos.${SECRET_DOMAIN}
            icon: immich.png
    - System:
        - Mikrotik:
            href: https://router.${SECRET_DOMAIN}
            icon: mikrotik-light.png
        - Proxmox:
            href: https://proxmox.${SECRET_DOMAIN}
            icon: proxmox-light.png
        - Mikrotik:
            href: https://nginxpm.${SECRET_DOMAIN}
            icon: nginx-proxy-manager.png
    - Extras:
        - Wavelog:
            href: http://wavelog.lan/
            icon: booklogr

  settings.yaml: |
    title: My Home Dashboard
    favicon: https://github.com/homarr-labs/dashboard-icons/blob/main/png/heimdall.png
    useEqualHeights: true
    theme: dark
    color: slate
    headerStyle: clean
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Smart Home:
        style: row
        columns: 3
        icon: mdi-home-analytics
      System:
        style: column
        icon: mdi-calendar
      Self hosted media:
        style: row
        columns: 3
        icon: mdi-multimedia
      System:
        style: row
        columns: 3
        icon: mdi-settings-outline
      Extras:
        style: row
        columns: 1
        icon: mdi-settings-outline
  widgets.yaml: |
    - logo:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/selfhosted-light.webp
    - search:
        provider: [duckduckgo]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Hey! Welcome!"
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - datetime:
        text_size: l
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h23
