---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-homepage
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HOMEPAGE_VAR_HASS_TOKEN }}"
        HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID: "{{ .HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID }}"
        HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID: "{{ .HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN: "{{ .HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN }}"

  dataFrom:
    - find:
        name:
          regexp: ^HOMEPAGE.*
