---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      homepage:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: &secret homepage-secret
          configmap.reloader.stakater.com/reload: &configmap homepage-config
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.3.2
            env:
              TZ: America/Los_Angeles
              HOMEPAGE_ALLOWED_HOSTS: "*"
            envFrom:
            - secretRef:
                name: *secret
            resources:
              requests:
                cpu: 15m
                memory: 200M
              limits:
                memory: 2G
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 3000
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
          nginx.ingress.kubernetes.io/satisfy: any
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.31.0/24
        hosts:
          - host: &host "{{ .Release.Name }}.internal.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
    serviceAccount:
      create: true
      name: *app
