---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.26.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-charts
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: false
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      create: true
    replicaCount: 2
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
    resources:
      requests:
        cpu: 15m
        memory: 192Mi
      limits:
        memory: 256Mi
