---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app proxies
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/default/proxies/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: proxies-secret
        kind: Secret
  prune: true
  retryInterval: 2m
  targetNamespace: *namespace
  timeout: 5m
  wait: false
