---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finance
components:
  - ./local_component/volsync
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./actual/ks.yaml
