---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gitea-runner
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      gitea-runner:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: gitea/act_runner
              tag: nightly-dind-rootless
            env:
              - name: DOCKER_HOST
                # value: tcp://localhost:2376
                value: unix:///run/user/1000/docker.sock
              # - name: DOCKER_TLS_VERIFY
              #   value: "1"
              # - name: DOCKER_CERT_PATH
              #   value: /certs/client
              - name: GITEA_INSTANCE_URL
                value: http://gitea.dev.svc.cluster.local:3000
              - name: GITEA_RUNNER_LABELS
                value: "docker:docker://catthehacker/ubuntu:act-latest"
            envFrom:
              - secretRef:
                  name: gitea-runner-secret
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 2Gi
            securityContext:
              privileged: true
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65536
    persistence:
      config:
        existingClaim: gitea-runner-vol
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
