---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoami
  namespace: network
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      whoami:
        replicas: 1
        containers:
          app:
            image:
              repository: docker.io/traefik/whoami
              tag: v1.11.0
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                memory: 32Mi
    service:
      app:
        controller: whoami
        ports:
          http:
            port: 80
    route:
      main:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: whoogle.png
          gethomepage.dev/name: Who Am I
          gethomepage.dev/group: Development
          gethomepage.dev/description: whoami service
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        hostnames:
          - whoami.${SECRET_DOMAIN}
