---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-v1
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: security
            name: infiscal-auth-secret
          clientSecret:
            key: clientSecret
            namespace: security
            name: infiscal-auth-secret
      # Details to pull secrets from
      secretsScope:
        projectSlug: k8s-xxym
        environmentSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: /v1
        recursive: true
      # optional
      hostAPI: https://app.infisical.com

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-homepage
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: security
            name: infiscal-auth-secret
          clientSecret:
            key: clientSecret
            namespace: security
            name: infiscal-auth-secret
      # Details to pull secrets from
      secretsScope:
        projectSlug: k8s-xxym
        environmentSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: /homepage
        recursive: true
      # optional
      hostAPI: https://app.infisical.com

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-authentik
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: security
            name: infiscal-auth-secret
          clientSecret:
            key: clientSecret
            namespace: security
            name: infiscal-auth-secret
      # Details to pull secrets from
      secretsScope:
        projectSlug: k8s-xxym
        environmentSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: /authentik
        recursive: true
      # optional
      hostAPI: https://app.infisical.com

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-auth-integrations
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: security
            name: infiscal-auth-secret
          clientSecret:
            key: clientSecret
            namespace: security
            name: infiscal-auth-secret
      # Details to pull secrets from
      secretsScope:
        projectSlug: k8s-xxym
        environmentSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: /auth-integrations
        recursive: true
      # optional
      hostAPI: https://app.infisical.com

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-postgres
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: security
            name: infiscal-auth-secret
          clientSecret:
            key: clientSecret
            namespace: security
            name: infiscal-auth-secret
      # Details to pull secrets from
      secretsScope:
        projectSlug: k8s-xxym
        environmentSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: /postgres
        recursive: true
      # optional
      hostAPI: https://app.infisical.com

