apiVersion: v1
kind: Service
metadata:
  name: &app immich
spec:
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: &port "{PROXY_IMMICH_PORT}"
---
kind: Endpoints
apiVersion: v1
metadata:
  name: *app
subsets:
  - addresses:
      - ip: ${PROXY_IMMICH_IP}
    ports:
      - port: *port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: *app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/exclude: true
    external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
spec:
  tls:
    - hosts:
        - &host photos.${SECRET_DOMAIN}"
  rules:
    - host: &host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich
                port:
                  name: http
