---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxies
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-v1
  target:
    name: proxies-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PROXY_AP_IP:  "{{ .PROXY_AP_IP }}"
        PROXY_AP_PORT:  "{{ .PROXY_AP_PORT }}"
        PROXY_HA_IP:  "{{ .PROXY_HA_IP }}"
        PROXY_HA_PORT:  "{{ .PROXY_HA_PORT }}"
        PROXY_NAS_IP:  "{{ .PROXY_NAS_IP }}"
        PROXY_NAS_PORT:  "{{ .PROXY_NAS_PORT }}"
        PROXY_FRIGATE_IP:  "{{ .PROXY_FRIGATE_IP }}"
        PROXY_FRIGATE_PORT:  "{{ .PROXY_FRIGATE_PORT }}"
        PROXY_IMMICH_IP:  "{{ .PROXY_IMMICH_IP }}"
        PROXY_IMMICH_PORT:  "{{ .PROXY_IMMICH_PORT }}"
        PROXY_JELLYFIN_IP:  "{{ .PROXY_JELLYFIN_IP }}"
        PROXY_JELLYFIN_PORT:  "{{ .PROXY_JELLYFIN_PORT }}"
        PROXY_PENPOT_IP:  "{{ .PROXY_PENPOT_IP }}"
        PROXY_PENPOT_PORT:  "{{ .PROXY_PENPOT_PORT }}"
        PROXY_ROUTER_IP:  "{{ .PROXY_ROUTER_IP }}"
        PROXY_ROUTER_PORT:  "{{ .PROXY_ROUTER_PORT }}"

  dataFrom:
    - find:
        name:
          regexp: ^PROXY.*
